# SERVIDOR
server.port=9753

# BASE DE DATOS - YUGABYTEDB
spring.datasource.url=jdbc:postgresql://us-east-1.0e993515-9e05-4bb5-b27c-fcea2e8bfb22.aws.yugabyte.cloud:5433/yugabyte?ssl=true&sslmode=require
spring.datasource.username=admin
spring.datasource.password=kD1CoyUx67E1lmBlvN4It8-Eftt7CP
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.jpa.properties.hibernate.implicit_naming_strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

# CORREO
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ca9214455@gmail.com
spring.mail.password=dfhs bzys qqgl udch
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# SWAGGER / SPRINGDOC
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.paths-to-match=/apiAlumnos/v1/alumnos/**,/apiAlumnos/v1/materias/**


# SERVIDOR
#server.port=9753

# BASE DE DATOS 
#spring.datasource.url=jdbc:mysql://localhost:3306/escuela_web_7cm3?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver

# JPA / HIBERNATE 
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
#spring.jpa.properties.hibernate.implicit_naming_strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

# CORREO
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=ca9214455@gmail.com
#spring.mail.password=dfhs bzys qqgl udch
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# SWAGGER / SPRINGDOC 
#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.paths-to-match=/apiAlumnos/v1/alumnos/**,/apiAlumnos/v1/materias/**

